---
- name: Install tomcat
  hosts: all
  become: yes
  tasks:
    - name: update ubuntu
      apt: 
        update_cache: yes
    - name: install java on ubuntu
      apt:
        name:
          - openjdk-11-jdk
        state: present
    - name: add a tomcat user
      ansible.builtin.user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: download tomcat ap tar file
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
        dest: /tmp
