---
- name: Install apache and php
  hosts: all
  become: yes
  tasks:
    - name: update ubuntu
      apt: 
        update_cache: yes
    - name: apache on ubuntu
      apt:
        name:
          - openjdk-11-jdk
        state: present
    - name: download foo.conf
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
        dest: /tmp