---
- name: Install tomcat
  hosts: all
  become: yes
  tasks:
    - name: update ubuntu
      apt: 
        update_cache: yes
    - name: install java on ubuntu
      apt:
        name:
          - openjdk-11-jdk
        state: present
    - name: add a tomcat user
      ansible.builtin.user:
        name: tomcat
        home: /opt/tomcat
        shell: /bin/false
        state: present
    - name: download tomcat ap tar file
      get_url:
        url: https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.54/bin/apache-tomcat-9.0.54.tar.gz
        dest: /tmp
    - name: untar the tomcat distribution
      ansible.builtin.unarchive:
        src: /tmp/apache-tomcat-9.0.54.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    - name: Find /var/log files equal or greater than 10 megabytes ending with .old or .log.gz
      find:
        paths: /opt/tomcat/apache-tomcat-9.0.54/
        patterns: "*.sh"
      register: shfiles
    - name: print sh files values
      debug:
        var: shfiles
    - set_fact:
      tomcat_executables: "{{ shfiles.files | map(attribute='path') | list )}}"
    - name: print the values
      debug:
        var: tomcat_executables
   