---
- name: Install nopcommerce
  hosts: all
  become: yes
  tasks:
    - name: apt packages download
      apt: 
        update_cache: yes
        name: 
          - nginx
          - apt-transport-https 
          - aspnetcore-runtime-3.1
          - unzip
        state: present
    - name: Enable nginx service
      service:
        name: nginx
        enabled: yes
        state: started
    - name: download the debian file
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: install the debian package
      apt:
        deb: /tmp/packages-microsoft-prod.deb
    - name: Download nopcommerce
      get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.40.4/nopCommerce_4.40.4_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce440
        #mode: '0440'
    - name: Unarchive a file that is already on the remote machine
      ansible.builtin.unarchive:
        src: /var/www/nopCommerce440/nopCommerce_4.40.4_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce440
        remote_src: yes    
    - name: Creates directory
      file:
        path: /var/www/nopCommerce440
        state: directory
    - name: Create bin director
      file:
        path: /var/www/nopCommerce440/bin
        state: directory
    - name: Create logs director
      file:
        path: /var/www/nopCommerce440/logs
        state: directory
    - name: give ownership to nop user and group
      ansible.builtin.file:
        path: /var/www/nopCommerce440
        state: directory
        recurse: yes
        owner: root
        group: root
    - name: create nopCommerce service file
      ansible.builtin.copy:
        src: nopCommerce440.service
        dest: /etc/systemd/system/nopCommerce440.service
    - name: reload and enable nopcommerce
      ansible.builtin.systemd:
        name: nopCommerce440.service
        daemon_reload: yes
        enabled: yes
        state: started
      
   