---
- name: Install tomcat
  hosts: all
  become: yes
  tasks:
    - name: update ubuntu
      apt: 
        update_cache: yes
        name: 
          - nginx
          - apt-transport-https 
          - aspnetcore-runtime-3.1
          - zip
        state: present
    - name: Enable nginx service
      service:
        name: nginx
          enabled: yes
          state: started
    - name: Creates directory
      file:
        path: /var/www/nopCommerce440
        state: directory
    - name: download the debian file
      get_url:
        url: https://packages.microsoft.com/config/ubuntu/20.04/packages-microsoft-prod.deb
        dest: /tmp/packages-microsoft-prod.deb
    - name: install the debian package
      apt:
        deb: /tmp/packages-microsoft-prod.deb
    - name: Download foo.conf
      get_url:
        url: https://github.com/nopSolutions/nopCommerce/releases/download/release-4.40.4/nopCommerce_4.40.4_NoSource_linux_x64.zip
        dest: /var/www/nopCommerce440
        #mode: '0440'
    - unarchive:
      src: /var/www/nopCommerce440/nopCommerce_4.40.4_NoSource_linux_x64.zip
      dest: /var/www/nopCommerce440
      remote_src: True